# See https://pre-commit.com for more information
repos:
  - repo: local
    hooks:
      - id: ct-lint
        name: "Chart Test: Lint"
        language: docker_image
        pass_filenames: false
        types: ['file']
        files: '^charts/.*(\.ya?ml|\.tpl|\.helmignore|NOTES.txt)'
        entry: -u 0 quay.io/helmpack/chart-testing:v3.3.1 ct
        args:
          - lint